/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package psp_hlc_04_grupal.View;

import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import psp_hlc_04_grupal.Exceptions.CommonActions;
import psp_hlc_04_grupal.Exceptions.DesplazamientoListaDetalle;
import psp_hlc_04_grupal.Model.Clases.Asignatura;

/**
 *
 * @author chaob
 */
public class ventanaVisualizarDetalle extends javax.swing.JPanel {

    private DesplazamientoListaDetalle desplazamientoDetalle;

    public ventanaVisualizarDetalle() {
        initComponents();
        
        // Listener para detectar cuando el panel se muestra en el CardLayout
        this.addPropertyChangeListener("ancestor", evt -> {
            if (isShowing()) {
                cargarDatos();
            }
        });
        

        desplazamientoDetalle = new DesplazamientoListaDetalle();
        cargarDatos();

    }

    public void cargarDatos() {
        ArrayList<Asignatura> n;
        try {
            n = desplazamientoDetalle.obtenerAsignaturas();
        } catch (SQLException ex) {
            Logger.getLogger(ventanaVisualizarDetalle.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (n != null) {
            textCod.setText(String.valueOf(n.get(0).getCodAsig()));
            textNom.setText(n.get(0).getNomAsig());
            System.out.println(n.get(0).getNomAsig());
            textNota.setText(String.valueOf(n.get(0).getNota()));
        } else {
            JOptionPane.showMessageDialog(this, "No hay datos disponibles.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAnterior = new javax.swing.JButton();
        btnFinal = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textCod = new javax.swing.JTextField();
        textNota = new javax.swing.JTextField();
        textNom = new javax.swing.JTextField();
        guardarNota = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel1.setText("Datos Asignaturas");

        btnAnterior.setText("<-");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnFinal.setText("->>");
        btnFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalActionPerformed(evt);
            }
        });

        btnSiguiente.setText("->");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        btnInicio.setText("<<-");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Codigo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nota");

        textCod.setEditable(false);
        textCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodActionPerformed(evt);
            }
        });

        textNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNotaActionPerformed(evt);
            }
        });

        textNom.setEditable(false);
        textNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNomActionPerformed(evt);
            }
        });

        guardarNota.setText("Guardar nota");
        guardarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(guardarNota)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(25, 25, 25)
                                .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textCod, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInicio)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnterior)
                        .addGap(18, 18, 18)
                        .addComponent(btnSiguiente)
                        .addGap(18, 18, 18)
                        .addComponent(btnFinal)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardarNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnFinal)
                    .addComponent(btnSiguiente)
                    .addComponent(btnInicio))
                .addGap(22, 22, 22))
        );

        btnAnterior.getAccessibleContext().setAccessibleName("BackBTN");
        btnFinal.getAccessibleContext().setAccessibleName("EndBTN");
        btnSiguiente.getAccessibleContext().setAccessibleName("NextBTN");
        btnInicio.getAccessibleContext().setAccessibleName("BeginningBTN");
        textCod.getAccessibleContext().setAccessibleName("codTXT");
        textNota.getAccessibleContext().setAccessibleName("notaTXT");
        textNom.getAccessibleContext().setAccessibleName("nomTXT");
        guardarNota.getAccessibleContext().setAccessibleName("guardarNotaBTN");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        try {
            if (desplazamientoDetalle.avanzar()) {
                cargarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Se ha llegado al ultimo registro.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al avanzar: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalActionPerformed
        try {
            desplazamientoDetalle.irUltimo();
            cargarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al ir al último registro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnFinalActionPerformed

    private void textCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodActionPerformed

    private void textNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNotaActionPerformed

    private void textNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        try {
            desplazamientoDetalle.irPrimero();
            cargarDatos();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al ir al primer registro: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
         try {
            if (desplazamientoDetalle.retroceder()) {
                cargarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Se ha llegado al primer registro.");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al retroceder: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void guardarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarNotaActionPerformed
        try {
            double nuevaNota = Double.parseDouble(textNota.getText());
            desplazamientoDetalle.actualizarNotaActual(nuevaNota);
            JOptionPane.showMessageDialog(this, "Nota actualizada correctamente.");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "La nota debe ser un número.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al actualizar la nota: " + ex.getMessage());
        }    
    }//GEN-LAST:event_guardarNotaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnFinal;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton guardarNota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField textCod;
    private javax.swing.JTextField textNom;
    private javax.swing.JTextField textNota;
    // End of variables declaration//GEN-END:variables
}
